### ISSUE TITLE
No module named gremlin

### ISSUE THREAD

**Issue by syjzwjj** [fabsx00/joern-tools#16]
when execute joern-lookup , it turns out : 

Traceback (most recent call last):
  File "/usr/local/bin/joern-lookup", line 4, in <module>
    __import__('pkg_resources').run_script('joerntools==0.1', 'joern-lookup')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/EGG-INFO/scripts/joern-lookup", line 3, in <module>
    from joerntools.shelltool.LookupTool import LookupTool
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/joerntools/shelltool/LookupTool.py", line 4, in <module>
    from TraversalTool import TraversalTool
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/joerntools/shelltool/TraversalTool.py", line 3, in <module>
    from joerntools.shelltool.JoernTool import JoernTool
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/joerntools/shelltool/JoernTool.py", line 3, in <module>
    from joerntools.DBInterface import DBInterface
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/joerntools/DBInterface.py", line 2, in <module>
    from joern.all import JoernSteps
  File "/usr/local/lib/python2.7/dist-packages/joern-0.1-py2.7.egg/joern/all.py", line 2, in <module>
    from py2neo.ext.gremlin import Gremlin
ImportError: No module named gremlin

how to solve this problems?

**Comment by vaioco** [comment]
hi @syjzwjj ,
have you solved that issue? Which repository are you using for installing joern-tools ?

**Comment by syjzwjj** [comment]
@vaioco I use the docker images from https://hub.docker.com/r/mckeimic/joern/
And I've solve this issue by using neo4j-community-2.1.8-unix.tar.gz and neo4j-gremlin-plugin-2.1-SNAPSHOT-server-plugin.zip from https://github.com/fabsx00/python-joern/issues/14 

Hope someone can fix this problem and let other's avoid these annoyed dependency problem.

**Comment by verazuo** [comment]
I fixed this problem by following commands
```
pip uninstall py2neo
pip install py2neo==2.0
```
It looks like that the version of your py2neo doesn't match this rep as it only supports python2.
You can find the detail from this link : [https://stackoverflow.com/questions/42157270/gremlin-module-not-found](https://stackoverflow.com/questions/42157270/gremlin-module-not-found)

**Comment by iwanlebron** [comment]
@verazuo This method is no longer applicable, there is no version 2.0 available
